kind: pipeline
type: docker
name: MyChampions

trigger:
    event:
      -push

steps:
# docker image build
  - name: docker-build-and-push
    image: plugins/docker
    settings:
       dockerfile: Sources/Dockerfile
       context: Sources/
       registry: hub.codefirst.iut.uca.fr
       repo: hub.codefirst.iut.uca.fr/lou.broda/MyChampions
       username:
         from_secret: SECRET_REGISTRY_USERNAME
       password:
         from_secret: SECRET_REGISTRY_PASSWORD