// <auto-generated />
using System;
using Console_Champions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleChampions.Migrations
{
    [DbContext(typeof(StubbedContext))]
    partial class StubbedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Console_Champions.ChampionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChampionEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = 1,
                            Name = "Akali"
                        },
                        new
                        {
                            Id = 2,
                            Class = 2,
                            Name = "Aatrox"
                        },
                        new
                        {
                            Id = 3,
                            Class = 3,
                            Name = "Ahri"
                        });
                });

            modelBuilder.Entity("Console_Champions.SkinEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForeignChampion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ForeignChampion");

                    b.ToTable("SkinEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ForeignChampion = 1,
                            Name = "Stinger"
                        },
                        new
                        {
                            Id = 2,
                            ForeignChampion = 1,
                            Name = "Infernal"
                        },
                        new
                        {
                            Id = 3,
                            ForeignChampion = 1,
                            Name = "All-Star"
                        },
                        new
                        {
                            Id = 4,
                            ForeignChampion = 2,
                            Name = "Justicar"
                        },
                        new
                        {
                            Id = 5,
                            ForeignChampion = 2,
                            Name = "Mecha"
                        },
                        new
                        {
                            Id = 6,
                            ForeignChampion = 2,
                            Name = "Sea Hunter"
                        },
                        new
                        {
                            Id = 7,
                            ForeignChampion = 3,
                            Name = "Dynasty"
                        },
                        new
                        {
                            Id = 8,
                            ForeignChampion = 3,
                            Name = "Midnight"
                        },
                        new
                        {
                            Id = 9,
                            ForeignChampion = 3,
                            Name = "Foxfire"
                        });
                });

            modelBuilder.Entity("Console_Champions.SkinEntity", b =>
                {
                    b.HasOne("Console_Champions.ChampionEntity", "Champion")
                        .WithMany("Skins")
                        .HasForeignKey("ForeignChampion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("Console_Champions.ChampionEntity", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
